.TH "Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug/CMakeFiles/tp09tri.dir" 3 "Mercredi 26 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug/CMakeFiles/tp09tri.dir
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBdonnees\&.c\&.o\&.d\fP"
.br
.ti -1c
.RI "fichier \fBmain\&.c\&.o\&.d\fP"
.br
.in -1c
