.TH "Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug/CMakeFiles/3.23.2" 3 "Jeudi 20 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug/CMakeFiles/3.23.2
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBCompilerIdC\fP"
.br
.ti -1c
.RI "répertoire \fBCompilerIdCXX\fP"
.br
.in -1c
