.TH "Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug" 3 "Mercredi 26 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBCMakeFiles\fP"
.br
.in -1c
