.TH "Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug/CMakeFiles/3.23.2/CompilerIdC" 3 "Lundi 17 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /root/CLionProjectsTP/tp09tri/cmake-build-debug/CMakeFiles/3.23.2/CompilerIdC
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBCMakeCCompilerId\&.c\fP"
.br
.in -1c
