.TH "/root/CLionProjectsTP/tp09tri/donnees.h" 3 "Samedi 8 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/root/CLionProjectsTP/tp09tri/donnees.h
.SH SYNOPSIS
.br
.PP
\fC#include 'tri\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBLire\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBAfficher\fP (\fBITEM\fP *listItem)"
.br
.ti -1c
.RI "void \fBsetParametersI\fP (\fBITEM\fP *pe)"
.br
.ti -1c
.RI "void \fBChoix\fP (\fBITEM\fP *listItem)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void Afficher (\fBITEM\fP * listItem)"

.SS "void Choix (\fBITEM\fP * listItem)"

.SS "void Lire (int argc, char ** argv)"

.SS "void setParametersI (\fBITEM\fP * pe)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour tp09tri à partir du code source\&.
