.TH "/root/CLionProjectsTP/tp09tri/donnees.c" 3 "Samedi 8 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/root/CLionProjectsTP/tp09tri/donnees.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'tri\&.h'\fP
.br
\fC#include 'donnees\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBChoix\fP (\fBITEM\fP *listItem)"
.br
.ti -1c
.RI "void \fBwriteFile\fP (char *fname, \fBITEM\fP *listItem)"
.br
.ti -1c
.RI "int \fBreadFile\fP (char *fname)"
.br
.ti -1c
.RI "int \fBcompareAge\fP (const void *a, const void *b)"
.br
.ti -1c
.RI "int \fBcompareAgeDec\fP (const void *a, const void *b)"
.br
.ti -1c
.RI "int \fBcompareName\fP (const void *a, const void *b)"
.br
.ti -1c
.RI "int \fBcompareFirstname\fP (const void *a, const void *b)"
.br
.ti -1c
.RI "void \fBLire\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBsetParametersI\fP (\fBITEM\fP *pe)"
.br
.ti -1c
.RI "void \fBAfficher\fP (\fBITEM\fP *ListITEM)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void Afficher (\fBITEM\fP * ListITEM)"

.SS "void Choix (\fBITEM\fP * listItem)"

.SS "int compareAge (const void * a, const void * b)"

.SS "int compareAgeDec (const void * a, const void * b)"

.SS "int compareFirstname (const void * a, const void * b)"

.SS "int compareName (const void * a, const void * b)"

.SS "void Lire (int argc, char ** argv)"

.SS "int readFile (char * fname)"

.SS "void setParametersI (\fBITEM\fP * pe)"

.SS "void writeFile (char * fname, \fBITEM\fP * listItem)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour tp09tri à partir du code source\&.
