.TH "/root/CLionProjectsTP/tp09tri/donnees.h" 3 "Mercredi 26 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/root/CLionProjectsTP/tp09tri/donnees.h
.SH SYNOPSIS
.br
.PP
\fC#include 'tri\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBLire\fP ()"
.br
.ti -1c
.RI "int \fBAfficher\fP (\fBITEM\fP *listItem)"
.br
.ti -1c
.RI "void \fBsetParametersI\fP (\fBITEM\fP *pe)"
.br
.ti -1c
.RI "void \fBChoix\fP (\fBITEM\fP *listItem, int ind)"
.br
.ti -1c
.RI "int \fBwriteFile\fP (char *fname, \fBITEM\fP *listItem)"
.br
.ti -1c
.RI "int \fBreadFile\fP (char *fname, \fBITEM\fP **)"
.br
.ti -1c
.RI "void \fBLoadDisplay\fP (\fBITEM\fP *listItem, int ind)"
.br
.ti -1c
.RI "int \fBeffacer\fP (const char *filename)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int Afficher (\fBITEM\fP * listItem)"

.SS "void Choix (\fBITEM\fP * listItem, int ind)"

.SS "int effacer (const char * filename)"

.SS "void Lire ()"

.SS "void LoadDisplay (\fBITEM\fP * listItem, int ind)"

.SS "int readFile (char * fname, \fBITEM\fP ** List)"

.SS "void setParametersI (\fBITEM\fP * pe)"

.SS "int writeFile (char * fname, \fBITEM\fP * listItem)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour tp09tri à partir du code source\&.
