.TH "ITEM" 3 "Mercredi 26 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ITEM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tri\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBnom\fP [\fBMAX_NAME_FR\fP]"
.br
.ti -1c
.RI "char \fBprenom\fP [\fBMAX_PRENOM_FR\fP]"
.br
.ti -1c
.RI "int \fBage\fP"
.br
.ti -1c
.RI "struct \fBITEM\fP * \fBnext\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "int age"

.SS "struct \fBITEM\fP* next"

.SS "char nom[\fBMAX_NAME_FR\fP]"

.SS "char prenom[\fBMAX_PRENOM_FR\fP]"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour tp09tri à partir du code source\&.
