.TH "/root/CLionProjectsTP/tp09tri/main.c" 3 "Mercredi 26 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/root/CLionProjectsTP/tp09tri/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'donnees\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour tp09tri à partir du code source\&.
