.TH "/root/CLionProjectsTP/tp09tri/tri.h" 3 "Samedi 8 Octobre 2022" "Version 0.1" "tp09tri" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/root/CLionProjectsTP/tp09tri/tri.h
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBITEM\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBMAX_ITEM\fP   100"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define FALSE   0"

.SS "#define MAX_ITEM   100"

.SS "#define TRUE   1"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour tp09tri à partir du code source\&.
